# Generated by Django 5.1.2 on 2025-10-31 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_call_sid', models.CharField(max_length=100, unique=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_transcript', models.TextField(blank=True, help_text='What the user said during the call')),
                ('agent_responses', models.TextField(blank=True, help_text="AI agent's responses")),
                ('full_transcript', models.JSONField(blank=True, default=dict, help_text='Complete conversation transcript with timestamps')),
                ('overall_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('emotional_score', models.FloatField(blank=True, help_text='Overall emotional well-being score (0-25)', null=True)),
                ('stress_indicators', models.JSONField(blank=True, default=list, help_text='List of stress indicators detected')),
                ('call_status', models.CharField(blank=True, help_text='Twilio call status', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Call History',
                'verbose_name_plural': 'Voice Call Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_score', models.FloatField(default=0, help_text='Positive sentiment score')),
                ('negative_score', models.FloatField(default=0, help_text='Negative sentiment score')),
                ('neutral_score', models.FloatField(default=0, help_text='Neutral sentiment score')),
                ('emotions_detected', models.JSONField(blank=True, default=list, help_text="List of emotions detected (e.g., ['happy', 'anxious'])")),
                ('key_phrases', models.JSONField(blank=True, default=list, help_text='Important phrases that indicate mental health state')),
                ('contributes_to_phq9', models.BooleanField(default=True, help_text='Whether this call should contribute to PHQ-9 calculation')),
                ('mental_health_impact', models.FloatField(blank=True, help_text='Impact on overall mental health score (-25 to +25)', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_confidence', models.FloatField(default=0.0, help_text='Confidence score of the sentiment analysis (0-1)')),
                ('call_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='voice_calls.voicecallhistory')),
            ],
            options={
                'verbose_name': 'Call Sentiment Analysis',
                'verbose_name_plural': 'Call Sentiment Analyses',
            },
        ),
        migrations.CreateModel(
            name='VoiceCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('custom_prompt', models.TextField(blank=True, help_text="Custom focus for the AI conversation (e.g., 'stress management')", null=True)),
                ('first_message', models.TextField(blank=True, help_text='Custom greeting message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Call Schedule',
                'verbose_name_plural': 'Voice Call Schedules',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='voicecallhistory',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_histories', to='voice_calls.voicecallschedule'),
        ),
    ]
