# Generated by Django 5.1.2 on 2025-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AddField(
            model_name='testresult',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='audio_sentiment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
