# Generated by Django 5.1.2 on 2025-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_testresult_options_testresult_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='audio_analysis',
            field=models.JSONField(default=dict),
        ),
    ]
