# Generated by Django 5.1.2 on 2025-10-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_age_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +1234567890)', max_length=20, null=True),
        ),
    ]
