# Generated by Django 5.1.2 on 2025-11-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('mental_health', 'Mental Health'), ('psychology', 'Psychology'), ('wellness', 'Wellness & Self-Care'), ('stress_management', 'Stress Management'), ('mindfulness', 'Mindfulness & Meditation'), ('cognitive', 'Cognitive Science'), ('emotional_intelligence', 'Emotional Intelligence'), ('general_knowledge', 'General Knowledge')], max_length=50)),
                ('questions_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('mental_health', 'Mental Health'), ('psychology', 'Psychology'), ('wellness', 'Wellness & Self-Care'), ('stress_management', 'Stress Management'), ('mindfulness', 'Mindfulness & Meditation'), ('cognitive', 'Cognitive Science'), ('emotional_intelligence', 'Emotional Intelligence'), ('general_knowledge', 'General Knowledge')], max_length=50)),
                ('total_questions', models.IntegerField(default=20)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('skipped_answers', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('user_answers', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('question_number', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.quiz')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('mental_health', 'Mental Health'), ('psychology', 'Psychology'), ('wellness', 'Wellness & Self-Care'), ('stress_management', 'Stress Management'), ('mindfulness', 'Mindfulness & Meditation'), ('cognitive', 'Cognitive Science'), ('emotional_intelligence', 'Emotional Intelligence'), ('general_knowledge', 'General Knowledge')], max_length=50, null=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', '-average_score'],
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UsedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('mental_health', 'Mental Health'), ('psychology', 'Psychology'), ('wellness', 'Wellness & Self-Care'), ('stress_management', 'Stress Management'), ('mindfulness', 'Mindfulness & Meditation'), ('cognitive', 'Cognitive Science'), ('emotional_intelligence', 'Emotional Intelligence'), ('general_knowledge', 'General Knowledge')], max_length=50)),
                ('question_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'genre'], name='games_usedq_user_id_a38246_idx')],
                'unique_together': {('user', 'genre', 'question_hash')},
            },
        ),
    ]
