# Generated by Django 5.1.2 on 2026-02-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGameLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('memory_match', 'Memory Match'), ('pattern_recognition', 'Pattern Recognition'), ('logic_puzzle', 'Logic Puzzle')], max_length=50)),
                ('total_games', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_time', models.FloatField(blank=True, null=True)),
                ('total_time_played', models.FloatField(default=0.0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', '-highest_score'],
                'unique_together': {('user', 'game_type')},
            },
        ),
        migrations.CreateModel(
            name='MiniGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('memory_match', 'Memory Match'), ('pattern_recognition', 'Pattern Recognition'), ('logic_puzzle', 'Logic Puzzle')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(help_text='Time in seconds')),
                ('moves_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'time_taken'],
                'indexes': [models.Index(fields=['user', 'game_type'], name='games_minig_user_id_669653_idx'), models.Index(fields=['-score'], name='games_minig_score_0c17c0_idx')],
            },
        ),
    ]
